arm_joint_controll:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Joint Position Controllers ---------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_1_joint
    pid: {p: 4200.0, i: 1, d: 220.0}
    
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_2_joint
    pid: {p: 8600.0, i: 100.0, d: 500.0}
    
  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_3_joint
    pid: {p: 5000.0, i: 200.0, d: 970.0}
    
  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_4_joint
    pid: {p: 80.0, i: 4.0, d: 20.0}

  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_5_joint
    pid: {p: 2500.0, i: 2.0, d: 40.0}
    
  joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_6_joint
    pid: {p: 30.0, i: 1.0, d: 5.0}
    
  # Griper Position Controllers --------------------------------
  joint_griper_right_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_right_arm
    pid: {p: 100.0, i: 10.0, d: 10.0}
    
  joint_griper_left_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_left_arm
    pid: {p: 100.0, i: 10.0, d: 10.0}
