arm_joint_controll:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Joint Position Controllers ---------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_1_joint
    pid: {p: 4000.0, i: 1, d: 200.0}
    
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_2_joint
    pid: {p: 8000.0, i: 500.0, d: 200.0}
    
  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_3_joint
    pid: {p: 4500.0, i: 400.0, d: 980.0}
    
  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_4_joint
    pid: {p: 40.0, i: 4.0, d: 10.0}

  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_5_joint
    pid: {p: 1500.0, i: 20.0, d: 150.0}
    
  joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_6_joint
    pid: {p: 20.0, i: 5.0, d: 8.0}
    
  # Griper Position Controllers --------------------------------
  joint_griper_right_position_controller:
    type: effort_controllers/JointPositionController
    joint: griper_arm_right_joint
    pid: {p: 50.0, i: 2.0, d: 30.0}
    
  joint_griper_left_position_controller:
    type: effort_controllers/JointPositionController
    joint: griper_arm_left_joint
    pid: {p: 50.0, i: 2.0, d: 30.0}
